### ISSUE TITLE
canopennode as master(clinet)

### ISSUE THREAD

**Issue by hunybal** [CANopenNode/CANopenNode#1]
hi 
i wana use canopennode stack for stm32f4 to control other devices(servers or slaves) via sdo Protocol
but I've afew problem about it.
1- what is the process for config sdo?
2- what is the process for sending a sdo massage and check the respond packet for being sure about that writing to object dictionary of slave done correctly ?
3- I cant find any practical help or pdf for using this stack
thanks for helping me

**Comment by CANopenNode** [comment]
Basic standard for CANopen is CiA301, which is freely available from http://www.can-cia.org/. But according to my opinion, it is better to read one of the books, describing CANopen.

There are some easy to use commercial tools for CANopen master. CANopenNode could also be a master, but it is not yet prepared to be a nice tool. There is also no practical help yet.
