### ISSUE TITLE
Documentation generation does not seem to work

### ISSUE THREAD

**Issue by ArminBmrt** [CANopenNode/CANopenNode#115]
I am having some problems with CANopenNode which will probably be solved by reading the documentation. Problem is the doxygen creates a very basic page with only 'CANopenNode documentation' showing.

I am working on windows, doxygen 1.8.16 (from http://www.doxygen.nl/download.html).

I open doxywizard, open 'Doxyfile' in the canopen node directory and press 'run doxygen'. This gives the almost documentation page. I have attached the doxygen log.

[doxygen_log.txt](https://github.com/CANopenNode/CANopenNode/files/3797243/doxygen_log.txt)

**Comment by martinwag** [comment]
The main page is indeed empty. I get a menu tree on the left to select the items, wich works in my case. Have you checked for that?

**Comment by ArminBmrt** [comment]
Thanks they indeed in the menu tree. Thanks
