### ISSUE TITLE
TPDO not transmitted

### ISSUE THREAD

**Issue by qworkz11** [CANopenNode/CANopenNode#146]
Hi,
what is the correct tx-type setting for a TPDO when it is supposed to be sent when the objects mapped into it change? I thought it was 255, I have the following issue though: I have an object `controlword` which is mapped into a TPDO with said setting, but `CO_OD_RAM.controlword = some_uint16t` does not result in a PDO being sent.
When an event timer is set, though, the TPDO works just fine:
```
can1  303   [3]  0F 00 00
can1  303   [3]  0F 00 00
can1  303   [3]  5F 00 01
can1  303   [3]  5F 00 01
```

Receiving RPODs works as well.

**Comment by CaCtus491** [comment]
Are you using the EDS Editor in libedssharp? If so, you'll need to have the 'Change Of State' checkbox enabled for the relevant object dictionary entries under the Object Dictionary tab.

![image](https://user-images.githubusercontent.com/17428191/71933783-0ba0eb80-31f7-11ea-8b0d-a48ed6398ae7.png)

**Comment by qworkz11** [comment]
Yep, that was the issue. Thanks!
