### ISSUE TITLE
Wrong number of RX message buffers

### ISSUE THREAD

**Issue by gotocoffee1** [CANopenNode/CANopenNode#151]
The [calculation of the RX buffers](https://github.com/CANopenNode/CANopenNode/blob/f2283e3ca98650b321ae51a2d4e69e21dd45aa32/CANopen.c#L102) is missing the LSS features, should be:

```c
#define CO_RXCAN_NO_MSGS (1+CO_NO_SYNC+CO_NO_EMERGENCY+CO_NO_TIME+CO_NO_RPDO+CO_NO_SDO_SERVER+CO_NO_SDO_CLIENT+CO_NO_HB_CONS+CO_NO_LSS_SERVER+CO_NO_LSS_CLIENT)
```

**Comment by martinwag** [comment]
Whereever this got lost...

**Comment by gotocoffee1** [comment]
Yeah strange I guess the last change on this line was the TIME module, so maybe a merge conflict?!
Anyway, I will close this since it got merged.
