### ISSUE TITLE
[Question] SYNC Producer

### ISSUE THREAD

**Issue by qworkz11** [CANopenNode/CANopenNode#164]
Hi,

how do I get my node to produce SYNC messages? I've set `0x1006` (cycle period) to 1000us but I don't get any messages on 0x80...

Thanks!

**Comment by CANopenNode** [comment]
See CiA301: https://www.can-cia.org/groups/specifications/

You have to configure object `0x1005`: set bit 30 to 1 to enable sync producer.

**Comment by qworkz11** [comment]
Thanks, my bad for not having a look first. Unfortunately, though, I still don't see any SYNCs on candump... Is there anything else that needs to be configured for SYNCs to be active other than `CO_init()`?
