### ISSUE TITLE
Possible BUG in CO_HBconsumer.c

### ISSUE THREAD

**Issue by jdormand** [CANopenNode/CANopenNode#168]
I believe the idx checking in methods such as:
```
CO_HBconsumer_initCallbackHeartbeatStarted
CO_HBconsumer_initCallbackHeartbeatStarted
CO_HBconsumer_initCallbackRemoteReset
CO_HBconsumer_getState
CO_HBconsumer_getNmtState
```
is incorrect. The code in question is part of the bounds check of the `idx` parameter passed into these functions:
```
idx>HBcons->numberOfMonitoredNodes
```
I believe that `idx` is zero based and the check should therefore be `>=`

This really comes down to what the property `numberOfMonitoredNodes` means in relation to the array `monitoredNodes`. Conventional wisdom suggests that if the array was declared [4] then `numberOf...` should be 4 and valid indices would be 0-3, but just in case I missed some subtlety, I have checked further:

These properties are setup in `CO_HBconsumer_init()` which in my code is currently called with
`monitoredNodes` = `CO_HBcons_monitoredNodes`
`numberOfMonitoredNodes` = `CO_NO_HB_CONS`

`CO_HBcons_monitoredNodes` comes from the main CO object and ultimately references:
```
static CO_HBconsNode_t      COO_HBcons_monitoredNodes[CO_NO_HB_CONS];
```

`CO_NO_HB_CONS` comes from the EDSeditor created CO_OD.h/.c files (OD) and ultimate resolves to:
```
#define ODL_consumerHeartbeatTime_arrayLength               7
```

Either way, `numberOfMonitoredNodes` does appear to relate directly to the array length, so I believe that the `idx` checking is incorrect.

This theory also seems to be supported by code in `CO_HBcons_monitoredNodeConfig`:

```
if(idx >= HBcons->numberOfMonitoredNodes) return;
```

which implies that only values of `idx` upto n-1 (inclusive) are valid. So we have an inconsistency at the very least.

Also, numerous places in the code which loop this array use:

```
for(i=0; i<HBcons->numberOfMonitoredNodes; i++)
{
...
```
which also cements this argument I think.

**Comment by jdormand** [comment]
Just found this in comments which seems to support my theory
```
 * @param HBconsTime Pointer to _Consumer Heartbeat Time_ array
 * from Object Dictionary (index 0x1016). Size of array is equal to numberOfMonitoredNodes.
 * @param monitoredNodes Pointer to the externaly defined array of the same size
 * as numberOfMonitoredNodes.
 * @param numberOfMonitoredNodes Total size of the above arrays.
```

**Comment by CANopenNode** [comment]
You are right, there is a bug.
Fixed in split-driver branch.
Thank you.
