### ISSUE TITLE
Why function CO_TPDOsend(CO_TPDO_t *TPDO) does not specify the data length of tx buffer?

### ISSUE THREAD

**Issue by gonnamakeit** [CANopenNode/CANopenNode#176]
as follow:

        i = TPDO->dataLength;
	pPDOdataByte = &TPDO->CANtxBuff->data[0];
	ppODdataByte = &TPDO->mapPointer[0];

	/* Copy data from Object dictionary. */
	for(; i > 0; i--)
	{
		*(pPDOdataByte++) = **(ppODdataByte++);
	}

       TPDO->sendRequest = 0;
	//TPDO->CANtxBuff->DLC = TPDO->dataLength;  should be added??
	return CO_CANsend(TPDO->CANdevTx, TPDO->CANtxBuff);

update: the same with the SDO response transfer. I guess PDO, SDO, are all with the issue.

**Comment by CANopenNode** [comment]
You have to call CO_CANtxBufferInit() before CO_CANsend().

**Comment by gonnamakeit** [comment]
CO_TPDOsend(CO_TPDO_t *TPDO) is not funtion implemented by the stack user.  CO_CANtxBufferInit() does not be called ahead in the  funtion CO_TPDO_process(). 
WHY?
