### ISSUE TITLE
Another CAN driver named 'CCAN'(NOT CAN) in LPCOpen for 18xx,43xx

### ISSUE THREAD

**Issue by kazuki0824** [CANopenNode/CANopenNode#19]
I have to manage CANOpen with LPCXpresso4337 board , which has two independent CAN controllers.
But LPCOpen's implementation of CCAN is a bit different from CAN of LPC17xx. So CANOpenNode doesn't work in LPC43xx.

**Comment by CANopenNode** [comment]
Please take a look at new driver for LPC1768 (and mbed).
I can't support LPC devices.
