### ISSUE TITLE
Expedited SDO download fails w/o size indication

### ISSUE THREAD

**Issue by bruecke** [CANopenNode/CANopenNode#2]
While using a PLC from Frenzel+Berg, I noticed that the stack always assumes a data length of 4 bytes when a SDO download initiate message is received which has the size indication bit not set.
(excerpt from CO_SDO.c:806)

    /* Expedited transfer */
            if((SDO->CANrxData[0] & 0x02U) != 0U){
                /* is size indicated? Get message length */
                if((SDO->CANrxData[0] & 0x01U) != 0U){
                    len = 4U - ((SDO->CANrxData[0] >> 2U) & 0x03U);
                }
                else{
                    len = 4U;
                }

This results in an abort message, if the triggered data type is not exactly 32 bytes long!
Is this really the desired behaviour?

Changing the else-case to

                /* get message length from OD */
                else{
                    len = SDO->ODF_arg.dataLength;
                }
makes it work for me. This assumes the sender really knows what he is doing, the CO_SDO_writeOD() function will take as many bytes as needed*. Unfortunately the CIA-301 document does not say anything about this case, other that it exists.

Regards,
Kai

[* out of the 4 possible data bytes]

**Comment by CANopenNode** [comment]
You are right, If master doesn't provide length, it is safely to get length from the object dictionary.
Correctness of data is master responsibility.

Repository updated.
