### ISSUE TITLE
DLC not updated before send

### ISSUE THREAD

**Issue by JeroenWagenaar** [CANopenNode/CANopenNode#207]
Before sending the NMT message as master the DLC field should be updated.

` 
    /* Send NMT master message. */
    if (error == CO_ERROR_NO) {

        NMT->NMT_TXbuff->data[0] = command;
        NMT->NMT_TXbuff->data[1] = nodeID;
        NMT->NMT_TXbuff->DLC = 2;
        error = CO_CANsend(NMT->NMT_CANdevTx, NMT->NMT_TXbuff);
    }
`
the line below is added

`NMT->NMT_TXbuff->DLC = 2;
`

**Comment by CANopenNode** [comment]
DLC is set inside CO_CANtxBufferInit(). It must not be set in that place. DLC is controlled exclusively by driver.

**Comment by JeroenWagenaar** [comment]
Ok, thanks for the clarification.
