### ISSUE TITLE
PDO buffers init problem

### ISSUE THREAD

**Issue by Norcio** [CANopenNode/CANopenNode#222]
Some ID's in TPDO, and RPDO are not initialized properly (set to 0) in buffer because of datalenght=0, please check debug output. For tests I use [CO_OD.zip](https://github.com/CANopenNode/CANopenNode/files/5071004/CO_OD.zip) generated from [xdd.zip](https://github.com/CANopenNode/CANopenNode/files/5071020/xdd.zip) with latest libedssharp ![obraz](https://user-images.githubusercontent.com/68592418/90177989-91979d00-ddab-11ea-97ab-e3c7c4373a44.png)
It looks like parsing problem but I couldn't find any issues in generated CO_OD files. Any suggestions? Thanks

![Screenshot_1](https://user-images.githubusercontent.com/68592418/90176922-0a95f500-ddaa-11ea-88de-b9410014494a.jpg)

**Comment by CANopenNode** [comment]
I think, mapped variables in your PDOs are not enabled for PDO mapping. You will have to re-edit CO_OD with libedssharp and enable PDO mapping for object 0x6100, etc.

**Comment by Norcio** [comment]
Thank you. It was the cause.
