### ISSUE TITLE
F28069M (C2000), what does it take to have it working?

### ISSUE THREAD

**Issue by riscy00** [CANopenNode/CANopenNode#239]
TMS320F28069M (C2000), what does it take to have it working?

**Comment by geoffrey-vl** [comment]
You'd need to write your own driver that brings support for these TI chips. Read the documents for info about porting this library for your board.

**Comment by rubenverhoef** [comment]
You also have to change the memory related functions, like `CO_memcpySwap2`. This because the C2000 processor doesn't support `uint8_t`, it's smallest value is 16 bit.

**Comment by CANopenNode** [comment]
> This because the C2000 processor doesn't support uint8_t, it's **smallest value is 16 bit**.

There may be other incompatibilities in the stack for such chip. Probably they can be fixed, but there must be someone with knowledge about "smallest value is 16 bit" problem and testing capabilities.

**Comment by martinwag** [comment]
We've had this some time ago... https://github.com/CANopenNode/CANopenNode/pull/186

**Comment by CANopenNode** [comment]
I'm closing this issue for now. If there will be a real interest for this chips, we can try to support them too.

**Comment by kaushel** [comment]
> 

Do you have any updates on this? I've found a demo for 28335 but it's being done with SYS BIOS (TI's RTOS). I'm looking into a bare metal implementation.
