### ISSUE TITLE
Wrong value for CO_LSS_IDENT_FASTSCAN?

### ISSUE THREAD

**Issue by wilkinsw** [CANopenNode/CANopenNode#240]
According to the document here:
https://www.can-cia.org/fileadmin/resources/documents/proceedings/2008_pfeiffer.pdf

The CS for fastscan should be 0x81, but in CO_LSS.h it is 0x51 (which is 81 decimal).

I don't have access to the revision of DSP 305 that describes fastscan, could someone that does verify what that value should be? I'm currently working on implementing it in my project and want to make sure we're all on the same page.

**Comment by martinwag** [comment]
In DSP305, CS for LSS fastscan is 51h.
