### ISSUE TITLE
SDO upload / download - no timeout status return 

### ISSUE THREAD

**Issue by adamusx** [CANopenNode/CANopenNode#243]
Hello,

In the new version of can node (2.0) there is error in CO_SDOclientDownload / CO_SDOclientUpload functions: no return status 
CO_SDOcli_endedWithTimeout, so using it like here:
`		uint16_t timer1msDiff;
		do{
			 /* Calculate time difference */
			 timer1msDiff = timer1ms - timer1msPrev;
			 timer1msPrev = timer1ms;
			 ret = CO_SDOclientDownload(SDO_C, timer1msDiff*1000, 0, (CO_SDO_abortCode_t*)SDOabortCode,0,0);
		}while(ret > 0);
		CO_SDOclientClose(SDO_C);` 
it make infinity loop.

**Comment by CANopenNode** [comment]
There was the problem inside SDO client. Not return value, but something else. However, SDO client has been recently heavily tested, some fixes were made in several places in both: master and newOD branch. So this makes problems no more.
