### ISSUE TITLE
OD_COB_ID_TIME undeclared

### ISSUE THREAD

**Issue by fenugrec** [CANopenNode/CANopenNode#258]
Just another discrepancy  I think should to be tracked separately from the other tickets I'm involved in.

Currently (CANopennode 0c000b,   libedssharp gb3f85db ),  the 301-profile.xpd from libedssharp defines object 1012 like this :

`<CANopenObject index="1012" name="COB-ID time stamp object" objectType="7" PDOmapping="no" 
uniqueIDRef="UID_OBJ_1012"`
producing a CO_OD.h like this
```
/*1012, Data Type: UNSIGNED32 */
        #define OD_COB_IDTimeStampObject  .....
```

but CANopen.c is looking for something named `OD_COB_ID_TIME` . That would work with the examples/_project.xml because it has
`<CANopenObject index="1012" name="COB-ID TIME" objectType="7" memoryType="ROM" dataType="07" accessType="rw" PDOmapping="no" defaultValue="0x00000100">`
whcih results in a slightly different  CO_OD.h :

```
/*1012, Data Type: UNSIGNED32 */
      #define OD_COB_ID_TIME .......
```

**Comment by CANopenNode** [comment]
301-profile.xpd from libedssharp should be used only for CANopenNode V4.0 and above.
For older versions use `example/_project.xml`
See also #257
