### ISSUE TITLE
OD File Information

### ISSUE THREAD

**Issue by ChSotiriou** [CANopenNode/CANopenNode#271]
It looks like more info is needed on the generation of CO_OD .h/.c files.
1) How are these supposed to be generated in v2.0? (master)
2) How does that compare with the newOD?

**Comment by JuPrgn** [comment]
The best way to generate OD is https://github.com/robincornelius/libedssharp
The export type on Libedssharp can be selected via menu Preferences if I remember well. V2 and V4 export are really different. I could look further if you need more informations.

**Comment by ChSotiriou** [comment]
Thank you, I just found that too.
