### ISSUE TITLE
CO_SDOserver_init: Type does not match write operation (uint16_t and OD_set_u32)

### ISSUE THREAD

**Issue by Roegnoeroek** [CANopenNode/CANopenNode#273]
https://github.com/CANopenNode/CANopenNode/blob/fc817770974e31656eea89998f4f2c612432528a/301/CO_SDOserver.c#L350

https://github.com/CANopenNode/CANopenNode/blob/fc817770974e31656eea89998f4f2c612432528a/301/CO_SDOserver.c#L369

The type used for CanId_ClientToServer and CanId_ServerToClient holds fewer bytes than written by OD_set_u32. 
That leads to the upper bytes of OD_1200_SDOsrvPar - Sub1/Sub2 holding more or less undefined values if this particular configuration branch is taken.

**Comment by CANopenNode** [comment]
Thank you for information. I changed OD_set_u32() and similar from macro to static inline functions to avoid problems like this.

**Comment by CANopenNode** [comment]
I think, it is solved now.
