### ISSUE TITLE
Null pointer dereference

### ISSUE THREAD

**Issue by JuPrgn** [CANopenNode/CANopenNode#275]
I found some null pointer dereference on New OD I will propose a PR to fix some of them.

On this one there is a dereference before checking for `NULL` : 

https://github.com/CANopenNode/CANopenNode/blob/66d0e14ef4ac631894c5b4adc0441ef4406c2eb9/301/CO_SDOserver.c#L686-L691

Do you prefer to return at the beginning of the function checking the `NULL` parameters or do you want to keep only one exit point ?

**Comment by CANopenNode** [comment]
I think, it is better to just return on the beginning, it is simpler.
