### ISSUE TITLE
CO_Process calls CO_SDOserver_process with invariant pointer

### ISSUE THREAD

**Issue by Roegnoeroek** [CANopenNode/CANopenNode#278]
I think the argument in the line down below should be
`co->SDOserver + i`
or
`&(co->SDOserver[i])`

https://github.com/CANopenNode/CANopenNode/blob/66d0e14ef4ac631894c5b4adc0441ef4406c2eb9/CANopen.c#L1348

Cheers, have a great weekend!

**Comment by CANopenNode** [comment]
Fixed, thank you.
