### ISSUE TITLE
about CanOpenNode dictionnary editor

### ISSUE THREAD

**Issue by franck48** [CANopenNode/CANopenNode#280]
hello all,
i just dicover a C# programm named CanOpenNode dictionnary editor

not sure about the goal of it,
is it a tool to create CO_OD.C for embeded microcontroler project ?
or, perhaps it is necessary to edit manually this file to customize the node slave project ?

**Comment by geoffrey-vl** [comment]
Look for https://github.com/robincornelius/libedssharp, its a gui editor that generates your OD for CanOpenNode

**Comment by franck48** [comment]
perfect,
very usefull tool, thank you Geoffrey.

i remember my first work with CANopen, a very lonely moment !!!

**Comment by franck48** [comment]
about CanOpenNode dictionnary editor :
this usefull tool propose to generate source files for canopennode
  CO_OD.C and the header CO_OD.H
a parameter " TOOLS / PREFERENCES " permit to choose to generate filesz for CANOPENNODE V4 or LEGACY.
here,
https://github.com/CANopenNode/CANopenNode
it's V2.
so my question are,
witch parameter i muste choose for canopenNode v2 ?  V4 or LEGACY
where can i find canOpenNode V4 ?

once more, thank you for your help

**Comment by pirupic2** [comment]
Hi , I just already tested the New Object Dicctionary with the LEGACY option and it seems it will work fine for the "Old Style" version.
Great Job¡¡¡
