### ISSUE TITLE
PDO clarification

### ISSUE THREAD

**Issue by JuPrgn** [CANopenNode/CANopenNode#283]
Hi Janez,

Branch : `newOD `

I found something strange, `dataOD` seems to be copied into `buf` without initialisation here (L836) : 
https://github.com/CANopenNode/CANopenNode/blob/66d0e14ef4ac631894c5b4adc0441ef4406c2eb9/301/CO_PDO.c#L830-L841
Can you please clarify this ?

**Comment by CANopenNode** [comment]
Yes, there is a bug. dataRPDO should be copied to buf. It is fixed, thank you.
