### ISSUE TITLE
Compilation error on Windows 

### ISSUE THREAD

**Issue by gotocoffee1** [CANopenNode/CANopenNode#288]
Hello,
I had some time and wanted to try the new branch, I noticed that it uses c99 VLA arrays. [here ](https://github.com/CANopenNode/CANopenNode/blob/72e840429718ded8bb59c0012945ca54aeaa259f/301/CO_SDOclient.c#L556) and [here  ](https://github.com/CANopenNode/CANopenNode/blob/72e840429718ded8bb59c0012945ca54aeaa259f/301/CO_SDOclient.c#L1209) Unfortunately msvc does not support them and from c11 they are only optional in the standard.

A few ideas to solve that:

* use malloc / free -> not optimal for mostly embedded
* check compiler:
  ```c
  #ifdef _MSC_VER
      uint8_t* buf = _alloca(count + 2);
  #else
      uint8_t buf[count + 2];
  #endif
  ```
* fixed size buffer, since the max fifo size is known  -> probably the most portable
  on a desktop 1000 byte stack is not a problem
  on an embedded device that could lead to problems, but than again a VLA could worst case increase the stack ptr about the same amount

* something else (?!)

Maybe we can discuss what the best is, I can create a pull request when we find a appropriate solution.

By the way, what do you think about adding visibility macros to the functions, e.g.:

```c
#define CO_API

...

CO_API CO_SDO_return_t CO_SDOserver_process(CO_SDOserver_t *SDO,
                                     bool_t NMTisPreOrOperational,
                                     uint32_t timeDifference_us,
                                     uint32_t *timerNext_us);

```

That would it make possible to use CANopen Node as an DLL on windows and it would improve the loadtime of the *.so on linux.

**Comment by CANopenNode** [comment]
I think, we can use fixed size buffer (`CO_CONFIG_SDO_CLI_BUFFER_SIZE + something` in both cases).

I think, it is no problem if we add visibility macros. I didn't came across them yet, but they could be useful.
