### ISSUE TITLE
On the (im)possibility of using arrays of type VISIBLE_STRING

### ISSUE THREAD

**Issue by Roegnoeroek** [CANopenNode/CANopenNode#293]
Hi everyone,
I'm having trouble when defining an array object containing VISIBLE_STRING vars.
Let's have a look at what the EDSEditor generates for my array object 0x100A with 5 x 15 character strings.
Within the OD_RAM type definiton (looks good):
```C
char x100A_softwareVersion[5][16];
```
Assembling the object list (arguable, but ok):
```C
.o_100A_softwareVersion = {
        .dataOrig0 = &OD_RAM.x100A_softwareVersion_sub0,
        .dataOrig = &OD_RAM.x100A_softwareVersion[0][0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_R | ODA_STR,
        .dataElementLength = 15,
        .dataElementSizeof = sizeof(char)
    }
```
Let's see what CANopenNode does when reading a string (wrong access) :
https://github.com/CANopenNode/CANopenNode/blob/b76002ae2af6fac15b37fed78427ffb18ed27cb2/301/CO_ODinterface.c#L213-L215

That results in forwarding the base pointer by a single byte for each sub index and I basically get multiple versions of my first string with an increasing offset.
Is there a way to get it working w\o code changes which I didn't see ? 
Otherwise, either the generator or the CO interface will have to be changed, I guess. Maybe have a look at it.

Best regards!

**Comment by CANopenNode** [comment]
Correct should be:
`.dataElementSizeof = sizeof(char[16])`

I sent PR with fixes.
