### ISSUE TITLE
Detect  when RPDO is updated into the objectdictionary 

### ISSUE THREAD

**Issue by HansB71-arm** [CANopenNode/CANopenNode#296]
Is there a mechanism in the CANOpen stack to detect a PDO or SDO is updated in the objectdictionary? 
 
I could not find a mechanism for this. Therefor I made a modification in CO_RPDO_process:

void CO_RPDO_process(CO_RPDO_t RPDO, bool_t syncWas)
while(CO_FLAG_READ(RPDO->CANrxNew[bufNo])){
int16_t i;
uint8_t pPDOdataByte;
uint8_t** ppODdataByte;

        i = RPDO->dataLength;
        pPDOdataByte = &RPDO->CANrxData[bufNo][0];
        ppODdataByte = &RPDO->mapPointer[0];

        /* Copy data to Object dictionary. If between the copy operation CANrxNew
         * is set to true by receive thread, then copy the latest data again. */
        CO_FLAG_CLEAR(RPDO->CANrxNew[bufNo]);
        for(; i>0; i--) {
            **(ppODdataByte++) = *(pPDOdataByte++);
        }
if (CO_CONFIG_PDO) & CO_CONFIG_FLAG_CALLBACK_POST
    /* Optional signal to RTOS, which can resume task, which handles RPDO. */
    if(RPDO->pFunctSignalPost != NULL) {
        RPDO->pFunctSignalPost(RPDO->functSignalObjectPost);
    }
endif

The callback function RPDO->pFunctSignalPost is added. When the objectdictionary is updated a call back function is called which fires an event.
Is there another/better implementation to detect the objectdictionary is updated whitout changing the CanOpen stack?

**Comment by CANopenNode** [comment]
You are asking about CANopenNode v2.0 (at this moment it is a master branch). This version still has the old Object Dictionary principle. There may some customized solutions.... But there are no plans to extend the old version.

I would recommend new version, v4.0 (at this moment it is a newOD branch and will soon become master). There you can define own write function for Object Dictionary variable. And that write function is called by RPDO or by SDO or by application. So you always get notified. See examples in https://github.com/CANopenNode/CANopenSocket. See also https://github.com/CANopenNode/CANopenDemo, there will soon be better examples.
