### ISSUE TITLE
Enable/Disable features of stack

### ISSUE THREAD

**Issue by CoderOnWinks** [CANopenNode/CANopenNode#303]
Hi,

Is it possible to enable/disable some of the features of CANOpenNode stack. I am considering not to use NMT, LSS, CANOpen Gateway, CanOpen Safety feature set. Can i configure them not to build in stack. Please suggest.

Thanks

**Comment by geoffrey-vl** [comment]
Yes, it can do that for you but you need to setup your project as you intended. 
For example in V1.3 and V2 you are able to set Number of XXX in you OD.h file, and according to that some functionality could be ruled out. I'm not sure how it works in V4. I'm also not sure why you would want to disable NMT as you won't have any control over your device. For example you won't be able to turn it off remotely.
