### ISSUE TITLE
Is it possible to create Data Dictionary in runtime instead of compile time

### ISSUE THREAD

**Issue by CoderOnWinks** [CANopenNode/CANopenNode#304]
Instead of compiling the OD.c and OD.h file, is there a way to create the OD on runtime with the input xdd/xml format files.

**Comment by geoffrey-vl** [comment]
No, see https://github.com/CANopenNode/CANopenNode/issues/284

**Comment by CANopenNode** [comment]
In v4 it is possible to generate object dictionary in run time before CANopen initialization. But no implementation (yet).
