### ISSUE TITLE
CO_SDOclient_setup use

### ISSUE THREAD

**Issue by c0d3runn3r** [CANopenNode/CANopenNode#31]
I need to act as SDO master for multiple slave nodes.  For example, I am node ID 0x3.  I need to read (client upload) from node 0x8 and also from node 0x9.

Initially I call CO_SDOclient_setup() for each node ID that I will be reading from.  Then I call CO_CANsetNormalMode().

From what I can tell, every time change which node I am reading from, I need to call CO_SDOclient_setup() again.  However CO_SDOclient_setup calls CO_CANrxBufferInit() which is only supposed to be called in the communications reset section.  Hence switching from reading node 0x08 to 0x09 (for example) calls CO_CANrxBufferInit() after I have already exited the communications reset section, and the whole thing crashes.

Am I using this properly?  What is the correct way to select which node ID I wish to talk to?

If I only talk to one node, everything works fine.

**Comment by CANopenNode** [comment]
You are doing this properly, but using CAN hardware filters is one of the most complicated things and it is usually different for each hardware.

First you can disable hardware filters, it should work just fine, it don't requires much processor power. Follow "CANmodule->useCANrxFilters". In that case, you should configure no hardware in CO_CANrxBufferInit().

Some microcontrollers don't support changing CAN filters on the fly. You can see driver for PIC32, how this is implemented.
