### ISSUE TITLE
possibility of sdo upload big files over coconn domain type  > 10 MByte

### ISSUE THREAD

**Issue by apiller-jetter** [CANopenNode/CANopenNode#310]
Is the new coconn in principle able to upload larger files?

**Comment by CANopenNode** [comment]
Yes, I tested 10GB in virtual CAN interface in Linux, few hours, no problems. Block transfer is much more efficient, segmented transfer works too. See https://canopennode.github.io/md_test_test_report.html

**Comment by apiller-jetter** [comment]
Thanks for the hint. 
I had the problem that our SDO server (receiver) needs a stream size information. 
Unfortunately cocomm does not have this option, so I have extended the "CO_gateway_ascii.c" with a new command. 
"[<net>] set sdo_wr_size <value>          # Set default sdo write size.\n" \
I don't know that the best solution is, but it works. 
Does it make sense to enter this into the master?
I could upload to a brach, what do you mean?

**Comment by CANopenNode** [comment]
I don't like to add non-standard solutions.

**Comment by apiller-jetter** [comment]
I understand that.
How can I then send a file with a size information transfer via cocomm/SDO. 
Are there other options?

**Comment by CANopenNode** [comment]
Size information is part of the SDO message, it is optional. Actually cocomm don't know the size information of large data on the beginning of transfer (write). So maybe your solution may be simple and useful. Pleas make a pull request then.
