### ISSUE TITLE
CANopen Error

### ISSUE THREAD

**Issue by amrehab11** [CANopenNode/CANopenNode#319]
Hello, I just started using this package to be able to get more info about my CAN connection. I have 2 motor drivers that I need to connect them to a CAN Bus but the this error pops up:
```
./canopend[9886]: (CO_CANerror_rxMsgError) Socket error msg ID: 0x20000004, Data[0..7]: 0x00, 0x08, 0x00, 0x00, 0x00, 0x00, 0x60, 0x00 (can0)
./canopend[9886]: CAN Interface "can0" reached Tx Warning Level
./canopend[9886]: (CO_CANerror_rxMsgError) Socket error msg ID: 0x20000004, Data[0..7]: 0x00, 0x20, 0x00, 0x00, 0x00, 0x00, 0x88, 0x00 (can0)
./canopend[9886]: CAN Interface "can0" changed state to "Tx Passive"
./canopend[9886]: (CO_CANerror_rxMsgError) Socket error msg ID: 0x20000040, Data[0..7]: 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 (can0)
./canopend[9886]: CAN Interface "can0" changed to "Bus Off". Switching to Listen Only mode...
./canopend[9886]: (CO_CANerrorSetListenOnly) can0 Set Listen Only
```
So what does this mean? The drivers are terminated by 120 ohms from both sides.

**Comment by CANopenNode** [comment]
baud rates ?
try candump

**Comment by amrehab11** [comment]
Both drivers are set on 112500 and when I used candump there was no output.

**Comment by CANopenNode** [comment]
112500 is not typical for CAN. You should see something reasonable on candump (or some CAN log) first. See your CAN interface for information.

**Comment by amrehab11** [comment]
I changed it to 500 kbit/s and still not working.
