### ISSUE TITLE
Infinite loop in CO_LEDs_process

### ISSUE THREAD

**Issue by ConductedForce** [CANopenNode/CANopenNode#326]
I imagine this isn't normal but I wonder if I have a config issue somewhere.

**Comment by CANopenNode** [comment]
Can you explain more precisely?

**Comment by ConductedForce** [comment]
Within the `CO_LEDs_process()` function, it looped for a seemingly unlimited time. Right inside the `while (LEDs->LEDtmr50ms >= 50000)` section. I didn't spend much time on it as I want to try and get the core of CANopenNode to run on my device first.

**Comment by CANopenNode** [comment]
But there is also inside the loop:
`LEDs->LEDtmr50ms -= 50000;`

**Comment by ConductedForce** [comment]
When I had debugged it initially, it had near max value of a 32 int. Something over 4 million. It makes me wonder if I have an initial variable incorrectly set somewhere. It runs on the ticktimer for an STM32 where CO_process() runs every 1 ms.

**Comment by CANopenNode** [comment]
Maybe `CO_LEDs_init` have been missed. There is `memset(LEDs, 0, sizeof(CO_LEDs_t));`

**Comment by CANopenNode** [comment]
Or there was very large initial `timeDifference_us`.

**Comment by ConductedForce** [comment]
CO_LEDs_init is not present, which seems to be the issue, I will be testing it shortly.

**Comment by ConductedForce** [comment]
Ah, it is called but I passed over it.

**Comment by ConductedForce** [comment]
LEDtimer50ms is 0 before and after init. At some point before the first CO_LEDs_process, it becomes 4122282055. Everytime.

**Comment by CANopenNode** [comment]
Pointer escaped somewhere?

**Comment by ConductedForce** [comment]
I've been taking from the example and another CANopenNode port, which may be the issue. I have a 1ms time loop from a ported example and then I do what's in the while loop of main_blank.c which is 99.99% of the problem. Changing timeDifference_us to 1000 should patch it.

**Comment by ConductedForce** [comment]
That didn't fix it. It still has a large value and I can't find anywhere where it would be reset.

**Comment by ConductedForce** [comment]
I'm not certain what's wrong with my setup or configuration but its copied straight from the example directory, minus and extra 1ms timer loop. Have to move on from it.
