### ISSUE TITLE
Missing CANopenNode/example/IO.html

### ISSUE THREAD

**Issue by IhorNehrutsa** [CANopenNode/CANopenNode#329]
In https://github.com/CANopenNode/CANopenNode/blob/master/doc/traceUsage.md
```
For more info on using trace functionality see CANopenNode/example/IO.html file.
```

**Comment by CANopenNode** [comment]
This is extra functionality, not yet updated to the latest version.

**Comment by IhorNehrutsa** [comment]
Thanks for your work
