### ISSUE TITLE
XPD->ESD->od.c(od.h) loses data

### ISSUE THREAD

**Issue by IhorNehrutsa** [CANopenNode/CANopenNode#331]
1) Open https://github.com/CANopenNode/CANopenNode/blob/master/example/DS301_profile.xpd
1.1) Export od.c(od.h)

2) Export (eds from xpd) and save DS301_profile_from_xpd.eds from the DS301_profile.xpd
The DS301_profile_from_xpd.eds and https://github.com/CANopenNode/CANopenNode/blob/master/example/DS301_profile.eds are equivalent(the difference is only in time)
![image](https://user-images.githubusercontent.com/70886343/130237908-9240701d-ce72-4676-ae4a-252860d8b1eb.png)
Close the DS301_profile.xpd

3) Open DS301_profile_from_xpd.eds
3.1) Export od.c(od.h) and save as od_from_eds_from_xpd.c(od.h)
Left:od_from_eds_from_xpd.h       Right:od_from_xpd.h 
![image](https://user-images.githubusercontent.com/70886343/130239012-642c81e7-7ecd-424e-9b95-a2cd244b6086.png)

Export from eds loses data:
#define OD_CNT_SYNC_PROD 1
#define OD_CNT_STORAGE 1
#define OD_CNT_EM_PROD 1
#define OD_CNT_HB_PROD 1

**Comment by CANopenNode** [comment]
Project file is xdd or xpd file, it contains additional CANopenNode specific information. eds file is just exported file.
