### ISSUE TITLE
EMCY Consumer

### ISSUE THREAD

**Issue by NebulaDev16** [CANopenNode/CANopenNode#340]
We were exploring more on Emergency consumer functionality.
And found this existing issues - https://github.com/CANopenNode/CANopenNode/issues/156

1. Is 0x1028 OD entry is supported for emergency consumer functionality?
2. Currently we have setup 3 can nodes on virtual can interface -  Node 1 - canopend, Node 2 & 4 - demoDevice.

When the EMCY message is generated by Node 4 or 2, it is always received by node 1 only.
But we can see that EMCY consumer callback is registered in both canopend and demoDevice code.
So for example, why node 4 is not receiving the emergency message from node 2?

**Comment by CANopenNode** [comment]
If this is still actual, please re-open the issue.
