### ISSUE TITLE
Advice on how to access OD from other threads (freeRTOS)

### ISSUE THREAD

**Issue by SputnikTheMighty** [CANopenNode/CANopenNode#344]
Hi, 

I am using CANopenNode v2 in a multithreaded application on ESP32. At the moment, I am using queues to pass information to the main CANopen thread which changes the values in the object dictionary, but this is quickly becoming very messy.

What is the best way to access & change object dictionary values from non-CANopen threads running on the same device?

- Using queues to pass information to CANopen main thread to process.
- Using mutex `CO_LOCK_OD()` and directly editing the object dictionary.
- Use the SDO master to write the values to the device's own object dictionary.

The last option I quite unsure about. The way I understand it, you can use the SDOmaster functionality to edit the object dictionary of any node on the network. Does this include the device itself?

**Comment by martinwag** [comment]
You can use all three ways. Using SDO Master essentially checks for own node ID, does a lookup for the register and then uses the lock method to set the values. So regarding runtime, method two will be the most efficient. Otherwise, use what works best for your use case :-)
