### ISSUE TITLE
LSS store not possible in global mode, but config node ID is

### ISSUE THREAD

**Issue by geoffrey-vl** [CANopenNode/CANopenNode#347]
I'm experimenting with setting and storing node IDs in global mode.
I don't own the latest copy of Cia305. However, in earlier releases it states that for using both "configure node id" and "store" services: 

> The LSS master device is responsible to switch one and only one LSS slave device into LSS configuration
> state before requesting this service

In CANopenNode this is true for [LSS Store](https://github.com/CANopenNode/CANopenNode/blob/master/305/CO_LSSmaster.c#L522), but not for [LSS config node id](https://github.com/CANopenNode/CANopenNode/blob/master/305/CO_LSSmaster.c#L480).

Was that changed in a later Cia305 release? Or is there any other specific reason I'm not seeing?

**Comment by martinwag** [comment]
Current 305 has a bunch of UML stuff describing LSS state machine and communication, also some application examples. Without this, I would not have been able to implement LSS. This doesn't mean I didn't do mistakes...
Some time ago you could do a "buyout" of the non-released specs at CiA. I don't know if they still do that.

` but it does expect a store command before any node ID is being applied.`
After writing node ID 255 to the "pending Node ID" buffer, you need to exit LSS by sending LSS switch global waiting, then do a NMT reset **communication** to all nodes. This loads the pending node ID to active node ID, now all your devices should start and wait for fastscan.
If i remember correctly.

`only include a subset of the LSSID `
We do the same, we're only having own devices on the network, so serial number scan is sufficient.

` of our devices are by default on the same node ID `
Is this needed? Just ship them without ID (=255).
