### ISSUE TITLE
SDO Download returns "CO_SDO_RT_waitingResponse" but communication seems to be correct in candump

### ISSUE THREAD

**Issue by NebulaDev16** [CANopenNode/CANopenNode#352]
We were trying out SDO APIs for SDO write transaction. Please find the code for SDO client below

1.  SDO_ret = CO_SDOclient_setup(SDO_C,  CO_CAN_ID_SDO_CLI + node_id, CO_CAN_ID_SDO_SRV + node_id,                       node_id); //returns 0 i.e. successful
2.  SDO_ret = CO_SDOclientDownloadInitiate(globalVars.SDO_C, entry_index ,entry_sub_index,                                               entry_data_size, globalVars.SDOtimeoutTime,false);     //successful
3. count = CO_SDOclientDownloadBufWrite(globalVars.SDO_C, (const uint8_t*)buffer, buf_len); //buf write successful
4.  do {
                /*Download SDO message in loop*/
                SDO_ret = CO_SDOclientDownload(globalVars.SDO_C,
                                           1000000,             //timeDifference_us - sleep 1 second
                                            false,               //bufferPartial 
                                           &abortCode,
                                           &sizeTransferred,
                                           NULL);               //timerNext_us 

                sleep(1);
        } while ((SDO_ret > 0));

This loop runs for 15 times until globalVars.SDOtimeoutTime(15 seconds) is expired. All time we get SDO_ret as 1 "CO_SDO_RT_waitingResponse". At last it exits the loop with Error -9 (CO_SDO_RT_endedWithClientAbort - Why client is aborting the SDO transfer?) and abort code 84148224 (Abortcode - CO_SDO_AB_TIMEOUT | 0x05040000, SDO protocol timed out)

Although, we can see in candump, response is received by server correctly.
<0x606> [8] 23 10 21 01 22 00 00 00
<0x586> [8] 60 10 21 01 00 00 00 00
### <0x606> [8] 80 10 21 01 00 00 04 05

Am I using the APIs incorrectly or checking the return code in incorrect way?
Why Node acting as SDO client raising 606 message with timeout error code?

Quick help is highly appreciated.

**Comment by ashirpa** [comment]
I am facing a similar issue.
Could you please a bit more detailed resolution on this issue?
Really appreciate if I can get some sample code in the context motioned (with interrupt support).
