### ISSUE TITLE
TPDO object reading on microcontroller

### ISSUE THREAD

**Issue by Irfan-str** [CANopenNode/CANopenNode#357]
I would like to know the template to read the TPDO object. I use STM microcontroller with CANOpen node. One CAN module sends TPDO message. Can you please provide a template to read the PDO message from the CAN module

**Comment by royazriel** [comment]
I am new to canopen.
found https://github.com/Jexbat/CANopenSTM32-HAL with sample of push button and leds.
from reading the code it is clear there are object dictionary entries for push button and for leds.
it is not clear how exactly one should run this setup.
my guess is you can run the sample on two stm32 boards connected to each other by 2 wires of CAN.
probably each board should get different node id in intialization.
can someone confirm ?
I am asking myself how the object data is being updated in both devices when I change a OD global value. I am not supposed to implicitly configure the node id I want to trasmit the message to ?
I have read basic tutorial about open CAN. it is stilll not clear. Also tutorials of CanopenNode are not so clear to me.
I have tried to read several code examples, but stil struggleing to understand how exactly its working.
will be glad if someone can give me some directions.
