### ISSUE TITLE
Enum is not guaranteed to be 32 bits.

### ISSUE THREAD

**Issue by liampwll** [CANopenNode/CANopenNode#360]
As per the C standard an enum is only guaranteed to be able to store values that can also be stored by int and int has a minimum size of 16 bits. In these two locations it is assumed to be 32 bits (or 16 bits unsigned in the latter case): https://github.com/CANopenNode/CANopenNode/blob/8c7d852902b2d307e8b91a43332c14e366641e00/301/CO_SDOserver.h#L336-L407
https://github.com/CANopenNode/CANopenNode/blob/8c7d852902b2d307e8b91a43332c14e366641e00/301/CO_ODinterface.h#L66-L114

This breaks CANopenNode on most 8-bit and 16-bit microcontrollers. Additionally the printf statements in the gateway code all make the same assumption.

**Comment by CANopenNode** [comment]
This is advanced functionality: If required, this might be ported for use on 8 or 16 bit microcontrollers too.
