### ISSUE TITLE
Send PDO in COS?

### ISSUE THREAD

**Issue by lenkapolaskova** [CANopenNode/CANopenNode#361]
Hi,
is this library capable of sending PDO on change of state? If I look in OD_attributes_t I don't see it as on of the setting. I can see that TPDO could be sent on event timer (configurable in object 0x1800) or if some flagPDObitmask flag exist for that object. I have custom OD where there is a record with entries mapped as TRPDO that has to be sent on parameter change.
Thank you

**Comment by pseudogelb** [comment]
I would also like to know how this works with COS in the new library. In the previous one, this could be activated in the OD Editor, but now I cannot find anything about COS
