### ISSUE TITLE
Setting string OD entries in self object dictionary

### ISSUE THREAD

**Issue by NebulaDev16** [CANopenNode/CANopenNode#364]
Hello, 

We are trying to read/write string OD entry (Index & Subindex combination) through OD_get_value() & OD_set_value().

Suppose OD entry (index - 0x2121 , subindex- 1) is of VISIBLE_STRING datatype. It is having default string "str" of 3 bytes. 

If we pass incorrect length(other than 3) in OD_get_value(), it returns errors as ODR_TYPE_MISMATCH.
###     if (stream->dataLength != len) return ODR_TYPE_MISMATCH;
Same is happening in OD_set_value() requires 3 as length even if we are overwriting it with 20 bytes string value.

Furthermore get after set also works only with 3 length not with updated 20 length (which is previously set).

Does this indicate that length parameter needs to be known before reading/writing the string? 
Or do we need to use other API to get/set string OD entries in self OD? (OD_getPtr() also has this check)

**Comment by martinwag** [comment]
Yep, length is fixed. You need to pre-define length at config time, after that you can only read and write strings with this length. This is to ensure that all bytes have defined values as there is no string-end (like \n or \0) in CANopen.
