### ISSUE TITLE
More than 4 TPDOs are making trouble

### ISSUE THREAD

**Issue by pseudogelb** [CANopenNode/CANopenNode#368]
Hi,

I have some trouble when I want to use more than 4 TPDOs. I have chosen 
5 TPDOs with Address 0x180 + NodeId - 0x580 + NodeId and when I debug
this it seems, that for 0x580 + NodeId I never get the canNodeId correctly added
for the address. Now when I have a look at Canopen.c from line 1255, there are
some strange things going on. It will only loop an address for 0x180 - 0x480
and this seems to be programmed static. So I can easly fix it, but I would be glad,
if it picks the address I have chosen in the object dictionary. 

Further I get some disturbances on the 0x580 from SDOs, this seems to be a standard address for this.
When I change the SDO server parameters to 0x680, I still get the messages on 0x580. How can I change that?

**Comment by dennisschagt** [comment]
The CANopen specification (CiA-301) includes the following table which indicates that the 5th PDO you try to configure (`0x580+NodeId`) falls in the range reserved for SDO transfers.

![image](https://user-images.githubusercontent.com/4629607/185748252-b9e0d67f-9cae-4c95-b7f5-c14267e8b7bb.png)
![image](https://user-images.githubusercontent.com/4629607/185748267-a363a41b-0f82-4df6-aac6-1c82348e301e.png)

Choosing any 5 addresses for your TPDOs in the regular PDO address range should be fine (provided there are no other devices on the CANopen network using those addresses). There is no requirement to have a 0x100 difference between different PDO addresses of a device.
