### ISSUE TITLE
can't find CO_driver.c

### ISSUE THREAD

**Issue by AnDigElectro** [CANopenNode/CANopenNode#378]
Hello I can't find CO_driver.c. There is CO_driver.h where is CO_driver.c?

**Comment by teixeirafms** [comment]
@AnDigElectro the file `CO_driver.cˋ is not provided as it is specific to the microcontroller you will be using.
There is an example here https://github.com/CANopenNode/CANopenNode/blob/master/example/CO_driver_blank.c
