### ISSUE TITLE
expériment and accuracy with CanOpenNode emergency message

### ISSUE THREAD

**Issue by franck48** [CANopenNode/CANopenNode#381]
hello ,
i need a little help,

i use CanopenNode on a Microchip 16bits Dsp ds33E,
sometimes, once very 1 or 2 days my device stop to work, return to pré-op state
and send an emergency message 

0x0B2  00 61 01 29

the node own the ID  32 so 0x80 + 0x32.

###Emergency message contents:
 *
 *   Byte | Description
 *   -----|-----------------------------------------------------------
 *   0..1 | @ref CO_EM_errorCodes.
 *   2    | #CO_errorRegisterBitmask_t.
 *   3    | Index of error condition (see @ref CO_EM_errorStatusBits).
 *   4..7 | Additional argument informative to CO_errorReport() function.

the ERROR CODE seems to be internal error
#define CO_EMC_SOFTWARE_INTERNAL        0x6100U /**< 0x61xx, Internal Software */

CO_errorRegisterBitmask indicate
CO_ERR_REG_GENERIC_ERR  = 0x01U, /**< bit 0, generic error */

 CO_EM_errorStatusBits indicate
#define CO_EM_ISR_TIMER_OVERFLOW        0x29U /**< 0x29, generic, critical, Timer task has overflowed */

very difficult to try to produce it whan i want,
i put an oscilloscope and put a little code for changing the state of a GPIO inside the IT TIMER,
it's very accurate : exactly 1ms

**Comment by JuPrgn** [comment]
Hi Franck

CAN bus warning appears when your error counters are above a limit this is detailed in CAN bus protocol error handling (not CANopen). This mean that you have some error on your frames (issues with frequency, bit timing, CAN bus length...) or this can happen if your node is momentary "alone" on a bus as his messages will not be acknowledged properly and then increase error counters.

**Comment by franck48** [comment]
hello JuPrgn,
i just update my message with more informations,
i do a mistake in my orginal message, the probleme seems to be around the IT-TIMER  1ms

**Comment by JuPrgn** [comment]
Given your description I guess your timer interrupt is sometimes interrupted by another one that block longer than 1ms and this occur every 1 or 2 days. You are right this is hard to debug... 
Can you change your other interrupts priority to be loyer than this timer ?  (CAN interrupt should still be higher priority than CAN Timer)

**Comment by franck48** [comment]
humm nice advice, once more mr thank you for your help,
i try it immediately.
i will post the result here

**Comment by JuPrgn** [comment]
You are welcome.
Hope this will helps you find it, good luck =)

**Comment by franck48** [comment]
Solution :
at the begining of the project i run CanOpenNode under FreeRtos taskS.
then, after remove it to keep code under 32k i put real-time process inside the same it-timer used by the stack.
but :
mr oscilloscope said :  i stay too long time inside it (sometimes), even with light treatment as it's mandatory to do.
the warning raised by CanOpenNOde was true....

from now, i just built a time base inside the it-timer,
all the code préviously inside the it is now in the main loop.

**Comment by JuPrgn** [comment]
Great nice you found it ! 
Don't forget to close the issue (you could also change the title to be more explicit) =)
