### ISSUE TITLE
Removing an old thread

### ISSUE THREAD

**Issue by AluminiumMan** [CANopenNode/CANopenNode#394]
Hi, I used to post on GitHub in my real name with an old account.

My account was deleted but my name is still signed on one of the posts. 

Can someone please help me either modify the old post or delete it for privacy reasons please?

How can I get in contact with a mod or admin to do this? I cant see any report button on the post

**Comment by CANopenNode** [comment]
I think, I can delete complete issue, but can't delete single post.

**Comment by CANopenNode** [comment]
Please verify, if it is solved.

**Comment by AluminiumMan** [comment]
Yes, appears to be resolved. Thank you

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by AluminiumMan** [comment]
Complete issue is fine

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
