### ISSUE TITLE
How to record received RPDO?

### ISSUE THREAD

**Issue by ytuemrah** [CANopenNode/CANopenNode#397]
Dear All,
I want to record, print RPDO data, I wonder about where exactly it is, which variable holds the RPDO data when the node received PDO message in CANopenDemo project.
Best Regards

**Comment by ytuemrah** [comment]
is ti about epoll, do I need kernel driver level diving?

**Comment by CANopenNode** [comment]
You have to map PDO to variables from object dictionary, then read or write the variable. See standard 301 or CANopen book or https://can-cia.org/can-knowledge/canopen/pdo-protocol/ or else.
