### ISSUE TITLE
producer heartbeat datalength DLC is zero

### ISSUE THREAD

**Issue by xenpac** [CANopenNode/CANopenNode#398]
In CO_NMT_Heartbeat.c, Line: 241, the heartbeat is send.

The current state is copied, but the DLC is left at 0.

shouldnt that be a DLC of 1 ?

**Comment by xenpac** [comment]
Ok, so anytime CANsend() is called, the DLC is always 0.
CANsend has to go through the Tx bufferlist to look for hte matching ID and get the DLC from there.
hmm

**Comment by xenpac** [comment]
ok sorry for the messup.

The Datalength is encoded in the message ID.
so DLC=(ID>>12)&0xfL;

The DLC member of the buffer-struct is not used!!

**Comment by CANopenNode** [comment]
DLC is configured via CO_CANtxBufferInit(). It is not necessary to configure DLC each time, when sending CAN message.

```/**
 * Send CAN message.
 *
 * @param CANmodule This object.
 * @param buffer Pointer to transmit buffer, returned by CO_CANtxBufferInit().
 * Data bytes must be written in buffer before function call.
 *
 * @return #CO_ReturnError_t: CO_ERROR_NO, CO_ERROR_TX_OVERFLOW or
 * CO_ERROR_TX_PDO_WINDOW (Synchronous TPDO is outside window).
 */
CO_ReturnError_t CO_CANsend(CO_CANmodule_t *CANmodule, CO_CANtx_t *buffer);
```

> The DLC member of the buffer-struct is not used!!
It depends on driver implementation.
