### ISSUE TITLE
XMC porting and RTR

### ISSUE THREAD

**Issue by microhenrio** [CANopenNode/CANopenNode#403]
I'm currently making a port of CANopenNode to the XMC Infineon microcontrollers. Looking to change the drivers, in the example https://github.com/CANopenNode/CANopenNode/blob/master/example/CO_driver_blank.c the functions CO_CANrxBufferInit(), CO_CANtxBufferInit() are setting the rtr bit of the frame ID.
But in the readme https://github.com/CANopenNode/CANopenNode/blob/master/README.md specifies that the RTR bit must not be used.
So, have I to check this bit in the sending ID's and send the messages with it activated or not?
Thanks.

**Comment by CANopenNode** [comment]
RTR bit is there only for completeness, but it is not used.
