### ISSUE TITLE
Communication error receive

### ISSUE THREAD

**Issue by EIC-VihangJani** [CANopenNode/CANopenNode#410]
I receive communication error every time from stack 
Could you give any guidance for it ? and I attach log file for your reference
[Uploading Test_1540_26-07-2022_0002.log…]()

26.07.22 : 15:47:14.042 : Test CAN    : CAN1  606 Tx SD  8  40 01 10 00 00 00 00 00
26.07.22 : 15:47:14.106 : Test CAN    : CAN1  586 Rx SD  8  4F 01 10 00 10 00 00 00
26.07.22 : 15:47:14.106 : Test Error  : OD 02: Accessing object 1001h:00h - Response value: 0x10, EDS default value: 0x00 failed.
26.07.22 : 15:47:14.106 : Test Notice : OD 02: Accessing object 1001h:00h - Response value: 0x10, EDS default value: 0x00 failed.

**Comment by Bartimaeus-** [comment]
Your log file didn't attach properly (it's just a link to this issue).

Index 0x1001 is the error register. It looks like bit 7 is set, indicating a manufacturer specific error

![image](https://user-images.githubusercontent.com/2954254/181061763-912dc2a2-424a-460e-bd95-a98b0f706955.png)

Interestingly CiA 301 specifies that bit 0 (generic error) should also be set when any of the other bits are set (my guess is that behavior isn't implemented by CANopenNode)
![image](https://user-images.githubusercontent.com/2954254/181062304-47c8a5f0-03a4-4797-8758-a116c89ac539.png)

you could try reading from index 0x1003 and see if there's additional info in the error fields:
![image](https://user-images.githubusercontent.com/2954254/181063024-3bb44ffd-b036-4e97-9a02-fce5f97a8765.png)

**Comment by EIC-VihangJani** [comment]
[TEST_1730_26-07-2022_0001.log](https://github.com/CANopenNode/CANopenNode/files/9194985/TEST_1730_26-07-2022_0001.log)

I attached the least file
