### ISSUE TITLE
How to create dynamic TPDO and RPDO in the code?

### ISSUE THREAD

**Issue by ankit-eic** [CANopenNode/CANopenNode#413]
Hi,

I would like to know, how could I create TPDO and RPDO dynamically into the code using API. Is this functionality available in the code?
If it is implemented how I can use it? Any hint or feedback would be nice for understanding code.

Thanks,
Ankit

**Comment by ankit-eic** [comment]
Hi,

Could I get any update on the above question? Thanks in advance.

Regards,
Ankit

**Comment by CANopenNode** [comment]
PDOs are configured dynamically with correct sequence of writing into object dictionary. See also https://www.can-cia.org/can-knowledge/canopen/pdo-protocol/

**Comment by ankit-eic** [comment]
> 



> PDOs are configured dynamically with correct sequence of writing into object dictionary. See also https://www.can-cia.org/can-knowledge/canopen/pdo-protocol/

Thanks for the reply. Is it possible to add new PDOs while the application is running?

**Comment by CANopenNode** [comment]
With some advanced programming, maybe yes.
