### ISSUE TITLE
NodeID is not available in SDO-Client struct (CO_CSDO)

### ISSUE THREAD

**Issue by KarstenSteingass** [CANopenNode/CANopenNode#417]
The NodeId of the client is not stored in the SDO-Client struct (CO_CSDO) and as such is not available in SDO transfer finalization callback.

My proposal is to add the nodeID to the struct in COCSdoEnable like this:

@@ -275,6 +275,7 @@ void COCSdoEnable(CO_CSDO *csdo, uint8_t num) {
        ((txId & CO_SDO_ID_OFF) == 0)){
        csdonum->TxId  = txId + nodeId;
        csdonum->RxId  = rxId + nodeId;
        csdonum->NodeId = nodeId;
        csdonum->State = CO_CSDO_STATE_IDLE;
    }
}

If this is acceptable I will generate a pull-request.

Best regards,
Karsten

**Comment by CANopenNode** [comment]
I don't understand the question?
Where is CO_CSDO or COCSdoEnable?
