### ISSUE TITLE
Wrong conditional compilation

### ISSUE THREAD

**Issue by franckinux** [CANopenNode/CANopenNode#420]
In file 301/CO_PDO.c at line 900 the conditional condition is wrong, it is not coherent with the timerNext_us function parameter.
Maybe the right one is 
#if (CO_CONFIG_PDO) & CO_CONFIG_RPDO_TIMERS_ENABLE
instead of 
#if (CO_CONFIG_SYNC) & CO_CONFIG_FLAG_TIMERNEXT

**Comment by CANopenNode** [comment]
Correct is
`#if (CO_CONFIG_PDO) & CO_CONFIG_FLAG_TIMERNEXT`

Fixed, thank you.
