### ISSUE TITLE
Port to ESP32 Arduino Core

### ISSUE THREAD

**Issue by thaanstad** [CANopenNode/CANopenNode#429]
Thanks for releasing this protocol layer!  Seems to work really well and has a good community of support.

I have implemented a port of this library to the ESP32 Arduino core if anyone has interest in utilizing the CANOpenNode library for Arduino and the ESP32 Wrover: 

https://github.com/thaanstad/ESP32_CanOpenNode.  

I have implemented and tested an example that utilizes PDOs, SDO_Client/server and HB producer.  Still having a few issues implementing the HB consumer in that the monitoring node is not going into pre-operational and not sending an emergency message.  I'll keep working on this since this is the last feature that I am interested in implementing for the project I am working on.  Perhaps this is just a configuration feature that needs to be enabled?

Is it possible to add this ESP32 port to the list of related projects?  I tried the other ESP32 port, and it was not up to date with the current ESP32 Arduino core so this would be helpful for others that are developing.

**Comment by CANopenNode** [comment]
deviceSupport.md upaded - point to this issue.
