### ISSUE TITLE
High/Low limit value entries not being written to object dictionary or outputting?

### ISSUE THREAD

**Issue by sametoktn** [CANopenNode/CANopenNode#430]
I'm using the EDSSharp editor and here the high and low limit values ​​entered for the object dictionary do not affect the output. I can't get a result on limiting the values ​​of the objects with the limits entered for High/Low. Can you provide some information about the functionality of this?

**Comment by CISSOIDjmr** [comment]
According to my findings, with EDSEditor v4.2.3, high/Low limit values are not being written to object dictionary (OD.h and OD.c). They are written in .eds and .dcf file (but not in .md).

CANopenNode defines CO_SDO_AB_VALUE_HIGH and CO_SDO_AB_VALUE_LOW but they are not used anywhere.
