### ISSUE TITLE
How can I get the COB-ID in the RPDO callback function?

### ISSUE THREAD

**Issue by yamamoto-kazusige** [CANopenNode/CANopenNode#446]
I have two nodes with COB-ID 0x38a, 0x38b. Each node sends Position actual value of 6064h with TPDO.

How can I get the COB-ID in the CANopenNode RPDO callback entry?
The callback function is declared as follows and can only get the data body.
```
ODR_t H6064_write(OD_stream_t *stream, const void *buf, OD_size_t count, OD_size_t *countWritten);
```

**Comment by robincornelius** [comment]
You don’t. It’s not part of the protocol not a limitation of the library. PDOs do not contain source information, you will have to configure one of your nodes to transmit on a different pod as there is no other way to tell them apart On 7 May 2023, at 09:14, Kazu ***@***.***> wrote:﻿
There are nodes with COB-ID 0x38a, 0x38b. Each node sends Position actual value of 6064h with TPDO.
How can I get the COB-ID in the CANopenNode RPDO callback entry?
The callback function is declared as follows and can only get the data body.
ODR_t H6064_write(OD_stream_t *stream, const void *buf, OD_size_t count, OD_size_t *countWritten);

**Comment by yamamoto-kazusige** [comment]
Thank you for your reply. I'll look into the device  settings.

**Comment by Mpic** [comment]
Well, CiA 301 still suggests that the source information (Node ID of the sender) is contained in the TPDO CAN-ID, which would be 180h + Node-ID for TPDO1 for the generic pre-defined connection set.
It would be useful to provide a generic "RPDO" callback with COB-ID to implement PDO reception efficiently for a great number of nodes (without having to define a specific RPDO for each sending node).
