### ISSUE TITLE
[Question]How to read RPdos asynchronously？

### ISSUE THREAD

**Issue by Ashenoneq** [CANopenNode/CANopenNode#451]
How to know when the RPDO is updated? Using polling is cpu wasteful. I found an RPDO callback, but after I registered the callback, the value of RPDO had not been updated to the object dictionary when the program entered the callback.

**Comment by pivodog** [comment]
You must call OD_writeOriginal to update the OD inside your callback.

**Comment by Ashenoneq** [comment]
@pivodog Thinks! I figure out!
