### ISSUE TITLE
how to send / receive PDO in ubuntu

### ISSUE THREAD

**Issue by Sugariscool** [CANopenNode/CANopenNode#455]
I am new in CANOpen.
I want to send a data array according to TPDO, and receive data by RPDO. 
I have noticed that I just should set the `TPDO->sendRequest = True;TPDO->transmissionType = 0x255;`
But how can I set my sent datas?
such as, send data: `uint8_t sendData[8] = {0x0a, 0x20, 0x06, 0x0a, 0x00, 0x00, 0x01, 0x0f};`
receive data array: `uint8_t recvData[8] = {0};`
which function should I use to send / receive PDO?
thanks for your answer！！

**Comment by martinwag** [comment]
You need some basic knowledge how CANopen is supposed to work, so I recommend getting a book: https://www.canopenbook.com/ . You can also ask ChatGPT, which in this case produced a correct, general answer :-)

User
how does a pdo in canopen work and how do i set it up?
ChatGPT

A PDO (Process Data Object) in CANopen is a communication object used for transmitting and receiving real-time data between nodes in a CANopen network. It is part of the higher-level communication protocol defined by the CANopen standard.

To understand how a PDO works, let's start with some basic concepts:

    Object Dictionary (OD): The Object Dictionary is a data structure that holds all the parameters, variables, and configuration information of a CANopen node. It is a standardized collection of objects defined by the CANopen standard.

    PDO Mapping: PDO Mapping defines which objects from the Object Dictionary are included in a PDO. It determines the data that will be transmitted or received by a node through a PDO.

    PDO Communication Parameters: Each PDO has communication parameters associated with it. These parameters include the PDO identifier (PDO ID), transmission type, and event-driven or time-triggered transmission settings.

Setting up a PDO involves the following steps:

    Define the Object Dictionary: First, you need to define the Object Dictionary for your CANopen node. This involves specifying the necessary objects, such as variables or parameters, that you want to include in the PDO.

    Configure PDO Mapping: Once the Object Dictionary is defined, you need to configure the PDO Mapping. This step determines which objects from the Object Dictionary will be included in each PDO. You can specify the PDO Mapping using configuration software or by modifying the Object Dictionary directly.

    Configure PDO Communication Parameters: Next, you need to configure the communication parameters for each PDO. This includes assigning a unique PDO ID, specifying the transmission type (e.g., synchronous, asynchronous), and setting the transmission trigger (event-driven or time-triggered).

    Enable PDO Transmission: After configuring the PDOs, you need to enable the transmission of PDOs on the relevant nodes in the network. This typically involves setting appropriate bits or flags in the CANopen communication stack or the node's firmware.

    Process PDO Data: Finally, you can read or write data to the PDOs. When a PDO is transmitted, the associated data from the Object Dictionary is serialized into a message and sent over the CAN bus. On the receiving side, the receiving node decodes the PDO message and updates the corresponding objects in its Object Dictionary.

It's worth noting that the exact procedure for setting up PDOs may vary depending on the specific CANopen device or software you are using. Consult the documentation or programming guides provided by the device manufacturer or software vendor for detailed instructions tailored to your setup.
