### ISSUE TITLE
How to control the node to switch NMT state through code?

### ISSUE THREAD

**Issue by Ashenoneq** [CANopenNode/CANopenNode#456]
My device is an NMT slave and I want to switch from operational state to pre-operational state. Is this possible?

**Comment by JuPrgn** [comment]
Hi you can select the NMT state after initialisation using OD entry 0x1F80 default value.

Bit 0 : select NMT Master (1) / Slave (0)
Bit 2 : After initialisation enter : Pre Operational (0) / Operational (1)

1F80 value : 
0x00 NMT Slave and Enter Pre Operational 
0x04 NMT Slave and Enter Operational

**Comment by Ashenoneq** [comment]
Thanks!
