### ISSUE TITLE
Reading of Visible String Result in SDO protocol timed out

### ISSUE THREAD

**Issue by Zeusz0** [CANopenNode/CANopenNode#465]
I want to read a Visible String data type, but I always get Abbort code 0504 0000h - SDO protocol timed out.

I guess that's because I have more than 4 bytes of data, but I think that should be handled by segment/block transfer. I am having trouble finding the instructions on how to set up the block/segmented transfer options.

**Comment by martinwag** [comment]
You need to initiate block/segmented transfer from the host side.

**Comment by chuxinyiyou** [comment]
> 您需要从主机端启动块/分段传输。

I would like to ask, how to start block/segment transfer from the host side?

**Comment by CANopenNode** [comment]
See CANopenDemo.
