### ISSUE TITLE
CO_SDO_t missing

### ISSUE THREAD

**Issue by ali-ghadyali-fvt** [CANopenNode/CANopenNode#470]
Compiling with -DCO_CONFIG_SRDO results in
`error: unknown type name ‘CO_SDO_t’; did you mean ‘CO_SRDO_t`

I cannot find the definition anywhere in the repo.

**Comment by funkobongrip** [comment]
This is related to CO_CONFIG_SRDO, if you disable SRDO it compiles fine.

**Comment by ali-ghadyali-fvt** [comment]
I need to work with a CIA304 device, Disabling SRDO will make it incompatible, right?

**Comment by CANopenNode** [comment]
CiA-304 only works in v1.3, not updated for the last version.

**Comment by temi54c1l8** [comment]
SRDO(CiA-304) is not implemented in v1.3, but is present in v2.0

**Comment by CANopenNode** [comment]
Now it works.
