### ISSUE TITLE
error handling on comms error

### ISSUE THREAD

**Issue by Jan-Jelle** [CANopenNode/CANopenNode#490]
what would be the most practical way to check for communication errors/heartbeat errors? i need to write all outputs to a required state (off) in case of any comms issue.

**Comment by CANopenNode** [comment]
Duplicate: https://github.com/CANopenNode/CanOpenSTM32/issues/54
In case of errors node goes into NMT pre-operational. Use CO_NMT_getInternalState().

**Comment by Jan-Jelle** [comment]
works like a charm. thanks!!
