### ISSUE TITLE
Porting SRDO to v4.0

### ISSUE THREAD

**Issue by temi54c1l8** [CANopenNode/CANopenNode#503]

**Comment by temi54c1l8** [comment]
[PortingSRDOto4.0.patch](https://github.com/CANopenNode/CANopenNode/files/14598593/PortingSRDOto4.0.patch)

**Comment by CANopenNode** [comment]
Can you please make a fork and a pull request. Please note, there already is a pull request for SRDO, but there is to many reformatting of the code, so I can't merge it directly: https://github.com/CANopenNode/CANopenNode/pull/487

**Comment by CANopenNode** [comment]
And please make it compliant with some [Misra C rules](https://github.com/CANopenNode/CANopenNode/blob/master/codingStyle), which was added recently: https://github.com/CANopenNode/CANopenNode/commit/a52db428f699394f58e12ce15acadfe1461e50ea

**Comment by temi54c1l8** [comment]
ready
