### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by arthurodamasceno** [CANopenNode/CANopenNode#508]
https://www.kalatec.com.br/wp-content/uploads/2021/10/INVT-SV-DA200-AC-Servo-Drive_CANopen-Technical-Guide.pdf

may i use this stack to control this servo driver? i'm totally lost, how do i setup TPDOS to send to servo driver commands?

**Comment by arthurodamasceno** [comment]
Or should i use SDOs?

**Comment by CANopenNode** [comment]
With SDO you configure parameters (drive parameters, configure PDOs, etc, store parameters). PDOs are used for exchange of data between CANopen devices. For configuration it is much easier, if you have a GUI tool. Usually manufacturers have something for their drives.

**Comment by CANopenNode** [comment]
If you send correct PDOs (which are basically a raw CAN messages), you can run your drive.
