### ISSUE TITLE
Simultaneous SDO Transactions

### ISSUE THREAD

**Issue by evilGitHub** [CANopenNode/CANopenNode#51]
I would like to know if it is possible with this stack to to multiple simultaneous SDO transactions.

Like reading from two different nodes at once. As I understand I have to call CO_SDOclient_setup every time my target changes before using CO_SDOclientDownloadInitiate or CO_SDOclientUploadInitiate. Is it somehow possible (like creating two instances of CO_SDOclient_t) to do to simultaneous transactions?

**Comment by CANopenNode** [comment]
I didn't try this, but it should work as you describe. (create two instances of CO_SDOclient_t inside CANopen.c, etc. Accessed nodes must be different.)

**Comment by evilGitHub** [comment]
Ok as this seems not to be intented I dont want to try it. I just channeld all SDO communications through a seperate Thread now.

Besides: Thanks for this great work!
