### ISSUE TITLE
How to make it possible to receive all messages (SDO, PDO, NMT) in raw form?

### ISSUE THREAD

**Issue by Chernobrovka** [CANopenNode/CANopenNode#511]
How to make it possible to receive all messages (SDO, PDO, NMT) in raw form (to transfer to another CO device) and at the same time have the CO node work on one CAN bus?

**Comment by martinwag** [comment]
simplest would be to modify your can driver to add a callback for rx and tx functions. this will give you a copy of each message to and from your device as raw can message.
