### ISSUE TITLE
Compiler warnings

### ISSUE THREAD

**Issue by rossb93** [CANopenNode/CANopenNode#512]
I currently get the 4 compiler warnings in my usage of CANopenNode:

`\301\CO_Emergency.c(374): warning: unused variable 'odRet' [-Wunused-variable]
  374 |     ODR_t odRet;
`

and 

`
305\CO_LSSslave.c(41): warning: 'CO_LSS_FASTSCAN_BIT0' is not defined, evaluates to 0 [-Wundef]
   41 | #if CO_LSS_FASTSCAN_BIT0!=0 || CO_LSS_FASTSCAN_VENDOR_ID!=0 || CO_LSS_BIT_TIMING_1000!=0
      |     ^
305\CO_LSSslave.c(41): warning: 'CO_LSS_FASTSCAN_VENDOR_ID' is not defined, evaluates to 0 [-Wundef]
   41 | #if CO_LSS_FASTSCAN_BIT0!=0 || CO_LSS_FASTSCAN_VENDOR_ID!=0 || CO_LSS_BIT_TIMING_1000!=0
      |                                ^
305\CO_LSSslave.c(41): warning: 'CO_LSS_BIT_TIMING_1000' is not defined, evaluates to 0 [-Wundef]
   41 | #if CO_LSS_FASTSCAN_BIT0!=0 || CO_LSS_FASTSCAN_VENDOR_ID!=0 || CO_LSS_BIT_TIMING_1000!=0
`

Proposed fixes are:
`
#if (CO_CONFIG_EM)
    ODR_t odRet;
#endif
`

so odRet is only used if CO_CONFIG_EM is not 0.

and

remove 

`
#if CO_LSS_FASTSCAN_BIT0!=0 || CO_LSS_FASTSCAN_VENDOR_ID!=0 || CO_LSS_BIT_TIMING_1000!=0
#error Inconsistency in LSS macros
#endif
`
as can't use #if directive with enums.

**Comment by CANopenNode** [comment]
Fixed as you proposed, `ODR_t odRet;` moved after `#if (CO_CONFIG_EM)...`

Thank you.
