### ISSUE TITLE
Seeking Guidance on Implementing User Input for Motor Control via PDO in CANopenNode

### ISSUE THREAD

**Issue by BLU3ERRY** [CANopenNode/CANopenNode#545]
I am a student currently studying motor control system design using CANopenNode. While exploring examples from CANopenDemo, I successfully managed to adjust the heartbeat message period using SDO commands by adapting the cocomm code.

Inspired by this, I would like to input data into the motor's target torque index through PDO using user input, similar to how I used ASCII commands via the gateway to perform write commands with SDO. However, I noticed that direct handling of PDO seems to be absent within the gateway, and I am unsure of the best approach to achieve this with CANopenNode.

I understand how to configure PDO mapping and set transmission types via SDO by examining the Object Dictionary. However, I am uncertain about whether I should be using TPDO or RPDO in this context. Additionally, I am struggling with how to structure the messages and implement this input handling in the gateway.

I would greatly appreciate any guidance or advice you could provide on this matter. Thank you for your time and assistance!

**Comment by martinwag** [comment]
`However, I noticed that direct handling of PDO seems to be absent within the gateway`

you need to implement a custom OD for the gateway that contains the variables you want to transmit/receive. You then access the OD variables by index, on whatever you mapped in the R/TPDOs.

`TPDO or RPDO ` T =transmit, R = receive

`Additionally, I am struggling with how to structure the messages`

have a look at how other devices do it :-)

**Comment by BLU3ERRY** [comment]
Thank you for your prompt response.

I am working on control calculations on the PC side, where the target torque is mapped to index 0x6071, subindex 0, and the data type is i16 (assuming the mapping is already completed). For instance, if I want to change the values of nodes whose RxPDO1 has a COB-ID of 0x202, would it be correct to send a message like "0x202 i16 $input" to the socket?

In the CANopenNode documentation for the CANopen gateway, it mentions support for the CiA309-3 ASCII command interface for NMT master, LSS master, and SDO client. It seems that the SDO client is implemented, as I was able to successfully send a command like "4 w 0x1017 0 u16 1000" through the socket and observe the correct SDO behavior. I am curious whether a similar approach would work for PDO commands. I apologize if my question is somewhat vague.

**Comment by martinwag** [comment]
you **never** write/read PDO directly, you only write/read the OD registers. The stack/gateway code will handle PDO generation for you, based on the changes made to the OD (respectively change the OD based on PDO reception).
ascii read example: [123] 1 r 0x1000 0x0 u32
ascii write example: [123] 1 w 0x1000 0x0 u32 456

**Comment by BLU3ERRY** [comment]
Thank you for your response.

I’m not entirely sure if I have fully understood, but it seems that if I want to directly input data, I should use SDO, while PDO is used for internal communication based on the information listed in the OD.

Thanks to your explanation, I feel I have gained a better understanding of CANopen. I appreciate your help!

**Comment by martinwag** [comment]
Yes, that's correct.

**Comment by martinwag** [comment]
If I understand you correct, that should be the case. Example:
OD 0x0001 -> TPDO 1 (Byte 0) -> CAN OID 0x181 -> RPDO 1 (Byte 0) -> OD 0x0002

Motor drivers and similar smaller devices PDOs can be statically mapped, so normally you set the mapping in the PLC.

**Comment by BLU3ERRY** [comment]
Thank you for your answers so far!
