### ISSUE TITLE
User defined PDO ID instead of predefined

### ISSUE THREAD

**Issue by SergeTauger** [CANopenNode/CANopenNode#551]
I'd like to specify my own COB ID for a PDO. In object dictionary editor I [set](https://github.com/CANopenNode/CANopenEditor) 0x190 for TPDO1 instead of predefined 0x280, but when TPDO is initialized the values is still 0x190, not 0x190 + node ID as I want to. Node ID is added to predefined TPDO COB ID [outside initialization](https://github.com/CANopenNode/CANopenNode/blob/fbd42d46a280b957c530c65ee6981c172fd6f635/CANopen.c#L1234) and user-specified one is[ kept "as is"](https://github.com/CANopenNode/CANopenNode/blob/fbd42d46a280b957c530c65ee6981c172fd6f635/301/CO_PDO.c#L1038). Is that done on purpose? At the moment I use such a workaround in communication reset, just after calling CO_CANopenInitPDO
```
	uint8_t active_node_id = CO->LSSslave->activeNodeID;
	for(size_t k=0; k < OD_CNT_RPDO; k++){
		CO_RPDO_t* pdo = CO->RPDO + k;
		uint16_t* pdo_can_id = &(pdo->PDO_common.configuredCanId);
		uint8_t  is_valid = pdo->PDO_common.valid;	
		if (is_valid){
			//Last 4 bits for node ID. Should be zero or node ID, otherwise it is OD editing error
			if(((*pdo_can_id) & CO_NODE_ID_Msk) == 0){
				*pdo_can_id |= active_node_id;
			} else if (((*pdo_can_id) & CO_NODE_ID_Msk) != active_node_id){
				return retval;
			}
		}
	}
```
and the same for TPDO, but it seems kinda dirty.

Best,
Serge.

**Comment by CANopenNode** [comment]
For non-standard behavior you could also make own CO_CANopenInitPDO() and use preDefinedCanId argument according to your needs. If preDefinedCanId is set, node_id will be added to cob_id, if those two are equal. Otherwise custom cob_id can be configured, independent of node_id.
