### ISSUE TITLE
How can I control this error: errorCode=0x8110, errorRegister=0x10, errorBit=0x14, infoCode=0x00000000?

### ISSUE THREAD

**Issue by BLU3ERRY** [CANopenNode/CANopenNode#553]
Thanks to your kind assistance, I have been diligently progressing with my project. However, I am repeatedly encountering an error. I suspect that it may be due to the buffer becoming full. Could you please help me identify the cause of this error and suggest possible solutions?

./canopend[2566]: CANopen device, Node ID = 0x00, starting
./canopend[2566]: CANopen command interface on local socket "/tmp/CO_command_socket" started
./canopend[2566]: CAN Interface "can0" RX buffer set to 477 messages (212992 Bytes)
./canopend[2566]: CANopen NMT state changed to: "initializing" (0)
./canopend[2566]: CANopen device, Node ID = 0x01, communication reset
./canopend[2566]: CANopen device, Node ID = 0x01, running ...
./canopend[2566]: CANopen NMT state changed to: "operational" (5)
./canopend[2566]: (CO_CANsend) Transmitting CAN msg OID 0x181 failed(can0)
./canopend[2566]: CANopen Emergency message from node 0x01: errorCode=0x8110, errorRegister=0x10, errorBit=0x14, infoCode=0x00000000
./canopend[2566]: CANopen NMT state changed to: "pre-operational" (127)
./canopend[2566]: (CO_CANsend) Transmitting CAN msg OID 0x701 failed(can0)
./canopend[2566]: (CO_CANsend) Transmitting CAN msg OID 0x701 failed(can0)
./canopend[2566]: (CO_CANsend) Transmitting CAN msg OID 0x701 failed(can0)
./canopend[2566]: (CO_CANsend) Transmitting CAN msg OID 0x701 failed(can0)
./canopend[2566]: (CO_CANsend) Transmitting CAN msg OID 0x701 failed(can0)

**Comment by martinwag** [comment]
I don't know about canopend/ canopenLinux, but the linux driver has a function that prints the kernel level error messages (https://github.com/CANopenNode/CANopenLinux/blob/e5655d1ce0a5377caab01567c9a0681f9d19b01d/CO_error.c#L235). You need to enable debug logging for that. There is a table in the kernel that shows how to decode the byte-code. Be aware that you can't match error messages to a specific tx request.

**Comment by CANopenNode** [comment]
Check also `candump can0` in separate terminal. Is there anything?

errorBit=0x14 means CO_EM_CAN_TX_OVERFLOW, see https://github.com/CANopenNode/CANopenNode/blob/fbd42d46a280b957c530c65ee6981c172fd6f635/301/CO_Emergency.h#L202C9-L202C30

Maybe there is something wrong with CAN. You must have at least two devices connected, don't forget the terminating resistors, ...

**Comment by robincornelius** [comment]
if this is happening when you put the bus into operational state, consider what you have configured as TPDOs when the node goes operational ALL TPDOs are transmitted if the inhibit time is 0 they are all essentially transmitted at the same time (or in a very short succession) which can overload the TX buffer as messages are ready to go out but there is no buffer space. The solution is to add a small inhibit value that is non zero to scatter the initial PDO transmission.

**Comment by BLU3ERRY** [comment]
Based on your assistance, I tried to resolve the issue today. However, when I attempted to fix the error using CANopenLinux, the heartbeat (HB) messages from the motor (node 2) appear normally on candump, but the HB messages from the PC (node 1) are not displayed. Despite this, there is a message indicating that it has entered the operational state. What should I do in this situation? Even after deleting and re-downloading the CANopenLinux and CANopenNode files, the error related to the HB messages persists.

**Comment by BLU3ERRY** [comment]
./canopend[3088]: (CO_CANsend) Transmitting CAN msg OID 0x701 failed(can0)

When I change the value of 0x1017 related to the producer HB message time, I notice that the frequency of that error messages changes. This suggests that there might be an issue with transmitting the HB messages. Additionally, although it indicates that it has entered the operational state, the TPDOs that were originally being transmitted properly do not seem to be sent anymore.

**Comment by BLU3ERRY** [comment]
I thought it would work, but only the USB to CAN is functioning, and the PCIe one isn't.. :<

**Comment by BLU3ERRY** [comment]
Following your instructions during the initial interface setup, I added loopback on berr-reporting on, and everything is working smoothly now. Thank you for your help. I will study harder and make better use of it.
