### ISSUE TITLE
minor compiler error in CO_SDOmaster.c

### ISSUE THREAD

**Issue by gotocoffee1** [CANopenNode/CANopenNode#56]
[line 687](https://github.com/CANopenNode/CANopenNode/blob/master/stack/CO_SDOmaster.c#L687) and [line 716](https://github.com/CANopenNode/CANopenNode/blob/master/stack/CO_SDOmaster.c#L716) should be at block start to guarantee compiler compatibility

**Comment by CANopenNode** [comment]
Is this still relevant?
Why #define instead of enum?

**Comment by CANopenNode** [comment]
Two lines are fixed in incoming commit
