### ISSUE TITLE
GPL License Questions #2 (socketCAN driver has no linking exception)

### ISSUE THREAD

**Issue by martinwag** [CANopenNode/CANopenNode#60]
Hi Janez,

currently, CANopenNode is marked in the Readme.md as using GPL with linking exception. This is true for all sources, except the socketCAN driver. Those are GPLv2.
I would like to use this driver (and fix some bugs/add features to it). However GPL means that I can't integrate it into my application, forcing me to build a completely new one.

Can we change that to the license that is used for the driver template?

Thanks!

**Comment by xoduddk123** [comment]
I posted a question on the [GPL License Questions](https://github.com/CANopenNode/CANopenNode/issues/57).
I also use socketCAN and I was surprised to see that it was only GPL v2.
I want socketCAN to be a GPL linking exception.

I'm sorry I do not have enough English. :)

Thanks!

**Comment by martinwag** [comment]
I know, I'm the one who answered your question :-)

**Comment by petmos** [comment]
Any news for this issue?
All sockcan files were commit on 10. Jan 2016 with " License changed to the GNU General Public License version 2 with the classpath exception."
But this exception wasn't included in these socketcan files.

**Comment by martinwag** [comment]
Got around this by writing my own...

https://github.com/martinwag/CANopenNode/tree/neuberger-master/stack/neuberger-socketCAN
