### ISSUE TITLE
Where do I download the Object Dictionary Editor?

### ISSUE THREAD

**Issue by xoduddk123** [CANopenNode/CANopenNode#62]
Hello.

I am using the Object Dictionary Editor to create Object data for use with CANopenNode.

However, I could not find the Object Dictionary Editor in a subproject at https://github.com/CANopenNode.

I was able to find the Object Dictionary Editor at https://sourceforge.net/projects/canopennode/files/canopennode/CANopenNode-3.10/.

My idea is that the repository has been moved from sourceforge to github.
Perhaps this Object Dictionary Editor is an old version.

When I check, CO_OD.c and CO_OD.h created by Object Dictionary Editor downloaded from sourceforge are declared as **LGPL**.
![object dictionary editor ver sourceforge](https://user-images.githubusercontent.com/10510127/30851195-d94efec4-a2e2-11e7-965d-6cd0b3d09d8a.png)

However, CANopenNode is a **GPL linking exception**.
https://github.com/CANopenNode/CANopenNode/blob/533801574055c5dacf60fb6b18930c288336dce1/example/CO_OD.c#L1-L50
https://github.com/CANopenNode/CANopenNode/blob/533801574055c5dacf60fb6b18930c288336dce1/example/CO_OD.h#L1-L50

This confuses me.
Where can I download the Object Dictionary Editor?

I'm sorry I do not have enough English. :)

Thanks!

**Comment by martinwag** [comment]
Use this one.

https://github.com/robincornelius/libedssharp

**Comment by xoduddk123** [comment]
Wow this is very good.
I was inconvenient to make it with firefox.
Thanks for telling me the location of [libedssharp](https://github.com/robincornelius/libedssharp).

**Comment by BarisYazici** [comment]
Any option for linux users?

**Comment by martinwag** [comment]
Yes, I'm using the editor in Linux. It is written in C# so you can just run (and compile) it in mono.
