### ISSUE TITLE
libedsharp CO_NO_NMT_MASTER

### ISSUE THREAD

**Issue by kenshail** [CANopenNode/CANopenNode#65]
Using the excellent libedsharp EDSeditor V0.5.2 or 6 beta I have one problem: I can not get either version to set CO_NO_NMT_MASTER to 1. I am using it with the .eds file that comes with CANopenSocket. Any suggestions?

**Comment by martinwag** [comment]
I think this is not supported in the GUI. Just set it manually inside the header files.

**Comment by robincornelius** [comment]
It does but it requires the appropriate master bits to be set in the OD

It requires Object 0x1f80 to exist and the value of object 0x1f80 must have
bit 0 set (eg have a value of 0x01)

See
https://github.com/robincornelius/libedssharp/blob/5c8f76f75f49c63db1757c9a359dc50c61b9184b/libEDSsharp/CanOpenNodeExporter.cs#L399

Regards

Robin

**Comment by kenshail** [comment]
Thank you Robin. That works fine.
 And thank you for the excellent editor.
