### ISSUE TITLE
Section in Readme.md describing commercial use

### ISSUE THREAD

**Issue by mwopfner** [CANopenNode/CANopenNode#7]
It would be useful to just have a section in the Readme.md file which states that the library can be used in commercial projects. I read the License description but was still unsure if it really allows to use it in a commercial project. But fortunately I found the discussion in the forum (https://sourceforge.net/p/canopennode/discussion/387151/thread/b7910450/) which discusses the issue.
So to make this more obvious to anybody a extra section would be helpful.

**Comment by CANopenNode** [comment]
I updated the readme. I hope, it is more clear now.

Thanks

**Comment by mwopfner** [comment]
Yes, it is clearer now.
