### ISSUE TITLE
Feature - PDO serial data streaming 

### ISSUE THREAD

**Issue by martinwag** [CANopenNode/CANopenNode#70]
Hi,

i've added a manual PDO mode to CANopenNode. This can be used for special use cases like serial data streaming via PDO where every PDO message must be delivered (like this gateway: https://www.ixxat.com/products/products-industrial/gateways-and-bridges/can-gw100-rs232).
This required me to do changes to PDO and CAN driver. This now contains a additional send function that checks for remaining queue space before sending.
This function is used when a PDO is sent. This applies to all TPDOs, not only the ones under user control!

I'm not sure if we want this changes in the mainline stack. Have a look at it, if we want it I can create a pull-request.

https://github.com/martinwag/CANopenNode/tree/add-manual-pdo

regards & have a nice christmas
Martin

**Comment by iurly** [comment]
Hi Martin,

I had a similar need. More precisely, I need the application to update some OD data and trigger the transmission of the TPDO which is currently using it.
Essentially, it's a CoS where, however, the actual data gets transmitted **even it's just the same value as before**.
I could explicitly set TPDO[x]->sendRequest but this means I would have to hardcode the TPDO mapping which I don't like. In my understanding the TPDO mapping could also be changed at runtime.

So my idea would be to call a function which gets the address of the OD_ variable that needs to be sent, then looks up all TPDOs for the ones who actually map it, and sets sendRequest for them accordingly. This means some extensive lookups every time one such variable gets changed though. Normally, I would get many of them at the same time.
As an alternative, for performance reasons, I could get the list (was actually thinking of a bitmask) of the involved TPDOs at initialization/remapping time (thereby performing the lookups just once), and triggering TPDO send requests by passing it the bitmask every time new data is available.
Would that make any sense to you?
Thanks!

**Comment by martinwag** [comment]
Hi,

I think, you can use my commit as a starting point. Be aware of the CAN driver modifications.

First, do you _really_ need all the flexibility? You don't have to do all the searching when you just set the mapping index to "ro" :-) . This is more or less what I'm doing.

Otherwise, I think your solution is OK. Get mapping at boot up and on change, and push this info into your application.

**Comment by iurly** [comment]
Hi,

it's not that I *really* need the flexibility. The thing is I don't want to hardcode the mapping when the same information is already specified in the OD.
Anyway, please have a look at https://github.com/iurly/CANopenNode/commit/c06909c7f621e0b0f7dd48b1d8d641f8b264aa55.

What I haven't found though is a way for the application to get notified of changed mappings.
Is there one at all?

Thanks!

**Comment by martinwag** [comment]
You don't get a notification for changed mappings. However, this is just a OD entry. You can register a callback for that. Keep in mind that this will overwrite the stacks own callback, so then you need to fix that.
