### ISSUE TITLE
Avoiding multibyte object split

### ISSUE THREAD

**Issue by kingd123** [CANopenNode/CANopenNode#73]
Hi folks,

CO_PDO.c lock/unlock as below are needed, no ?

```
int16_t CO_TPDOsend(CO_TPDO_t *TPDO){
:
    /* Copy data from Object dictionary. */
    CO_LOCK_OD();
    /* Prevent mid-use multibyte object dictionary item alter by interrupting item write */
    for(; i>0; i--) {
        *(pPDOdataByte++) = **(ppODdataByte++);
    }
    CO_UNLOCK_OD();  /* Allow object dictionary item alter */
:
}
```

This to prevent for example, interrupt when only _one_ byte of a uint16 object has been copied,
_then_ an interrupting user-code function _updates_ the uint16 in the OD, _then_ the above code
resumes and copies the second byte. Resulting in, the sent uint16 comprising an old and new byte,
which do not necessarily form a coherent whole, for the usage in question. At least, if you have an
interrupting routine that writes to the OD, as I have.

Of course, the same applies to any interrupted multibyte object copy. Such as a float, or a string
(max 8 bytes): If part old bytes, and part new bytes, are copied, the resultant sent whole might not
necessarily be coherent. Or even legitimate, for a float.

In CO_driver.h, lock/unlock macros defined for example thus:

```
#define CO_LOCK_OD()   __disable_irq( );  /**< Lock critical section when accessing Object Dictionary */
#define CO_UNLOCK_OD() __enable_irq( );   /**< Unlock critical section when accessing Object Dictionary */
```
Presently the stack uses just in SDO.c as below, same reason I'd guess:

```
uint32_t CO_SDO_readOD(CO_SDO_t *SDO, uint16_t SDOBufferSize){
:
    /* copy data from OD to SDO buffer if not domain */
    if(ODdata != NULL){
        CO_LOCK_OD();
        while(length--) *(SDObuffer++) = *(ODdata++);
        CO_UNLOCK_OD();
:
```
Best regards,

David

**Comment by martinwag** [comment]
Yes, they are needed, as this is basically a multithreaded program. If you go single threaded (meaning no interrupts), you don't need any locks.

**Comment by MartySchrader** [comment]
While I would guess it's okay to label anything with separate interrupt handlers as "multithreaded," the issue of split precision can also be addressed with semaphores or mutexes. For instance, if your background operation raised a semaphore every time it updated a value then the front end would always know if it had the latest value or not. As such:

Do
  Done = false
  Semaphore = false
  Copy value
  If (Semaphore is still false) then
    Done = true
While (Done is not true)

This is how the front end knows it has the latest, non-buggered-up value.
