### ISSUE TITLE
How to do porting With STM32L4xx series ??

### ISSUE THREAD

**Issue by pratapdevendra24** [CANopenNode/CANopenNode#84]
I am working with Stm32L476 and try to port current Version of CANopen with my project, But it is giving so many errors and warnings.

Is there any proper documentation in which I can get to know how to port with my project or How to use it ??

**Comment by JAYATEERTHA2018** [comment]
Hi folks,,,,

We have downloaded CANopen stack and trying to port it for STM32L476 series micro-controllers. But we are getting compiling errors as some files are missing in the above package. So could anyone please upload the latest available package which includes all dependent files and easily compilable..? 

Waiting for kind and earliest reply...!!!!!!!!

**Comment by martinwag** [comment]
The package itselve should be complete, I can compile it with gcc ARM. Maybe you have to add an include path to the makefile?

**Comment by pirupic** [comment]
Hi martingwag, 
which enviroment can be used to open the STM32 Project and compile with gcc ARM?
can be opened with  iar Workbench? or atollic, or keil?
Thanks in advanced

**Comment by martinwag** [comment]
I'm using the gcc arm embedded toolchain on linux. That's all you need. If you want a IDE, you can get SW4STM32 Eclipse based IDE from ST, this should include the toolchain.
However, it should work with one of the commercial toolchain vendors too...

**Comment by ad7718** [comment]
https://github.com/w1ne/CANOpenNode-CubeMX-HAL

**Comment by martinwag** [comment]
I think question is answered.
