### ISSUE TITLE
CANopen and stm32 with HAL

### ISSUE THREAD

**Issue by Barto22** [CANopenNode/CANopenNode#89]
Hi,
I'm new to CANopen node stack, I want to make it work with stm32 but I saw that the CO_driver is based on the standard library and I want to use HAL. Please help me guys what should I change and where should I start or if someone have working code for some stm32 with HAL could you send me it? At the beginng I want to make some kind of example like it is for PIC.
Best regards

**Comment by TheLamy** [comment]
Does anybody have a solution for this now? I'm also trying to write the driver on my own, but I'm struggling with it.

**Comment by StefanoPietrosanti** [comment]
I was planning on writing the driver later this year, I need to find the time for it. It is definitely something that will be useful for the new STM32 generation.

**Comment by ad7718** [comment]
https://github.com/w1ne/CANOpenNode-CubeMX-HAL

**Comment by martinwag** [comment]
I think question is answered.

**Comment by Mutharagan** [comment]
> I ported this https://github.com/w1ne/CANOpenNode-CubeMX-HAL to stm32f042, works fine. I only changed can instance and recalculated clocks regs for can.

Hi, 
I have included CANopen files with my project, some doubts,  have you mentioned CO_configurationMode() . What are the things need to be put in that function definition.

**Comment by martinwag** [comment]
Please open an new issue. No one will see messages added to a closed issue.
