### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by e135193** [CANopenNode/CANopenNode#90]
I am getting an error for the below code line in the **CO_CANrxBufferInit** function

`buffer->pFunct = pFunct;`

`Error[Pe513]: a value of type "void (*)(void *, CO_CANrxMsg_t )" cannot be assigned to an entity of type "void ()(void *, CanRxMsgTypeDef *)"`

Do you have the full CubeMx project that I can compile without a problem ?

**Comment by e135193** [comment]
Where should I put my CanTx() and CanRx() functions in the code ?

**Comment by martinwag** [comment]
Read the comments in the driver template. You need at least basic understanding as just putting rx/tx will not work.

**Comment by e135193** [comment]
I am able to port canopennode to new HAl/Cube version. However I have a problem. The node start sending heartbeat at first then stop sending any data. below is the can output.

What could be the problem ?

Sample Output #1
701 00 00 00 00 00 00 00 00
701 05 00 00 00 00 00 00 00
701 05 00 00 00 00 00 00 00
701 05 00 00 00 00 00 00 00
701 05 00 00 00 00 00 00 00
701 05 00 00 00 00 00 00 00
701 05 00 00 00 00 00 00 00
701 05 00 00 00 00 00 00 00
081 00 00 00 01 41 00 60 00
081 20 81 00 07 33 00 87 00
081 20 81 00 07 33 00 87 00
081 20 81 00 07 33 00 87 00
081 20 81 00 07 33 00 87 00
081 20 81 00 07 33 00 87 00
081 20 81 00 07 33 00 87 00
081 20 81 00 07 33 00 87 00
081 20 81 00 07 33 00 87 00
081 20 81 00 07 33 00 87 00
081 20 81 00 07 33 00 87 00
701 05 00 00 00 00 00 00 00
701 05 00 00 00 00 00 00 00
701 05 00 00 00 00 00 00 00
701 05 00 00 00 00 00 00 00
701 05 00 00 00 00 00 00 00
701 05 00 00 00 00 00 00 00

Sample Output #2
701 00 00 00 00 00 00 00 00
701 05 00 00 00 00 00 00 00
701 05 00 00 00 00 00 00 00
701 05 00 00 00 00 00 00 00
701 05 00 00 00 00 00 00 00
701 05 00 00 00 00 00 00 00
701 05 00 00 00 00 00 00 00
701 05 00 00 00 00 00 00 00
701 05 00 00 00 00 00 00 00
701 05 00 00 00 00 00 00 00
701 05 00 00 00 00 00 00 00
701 05 00 00 00 00 00 00 00
701 05 00 00 00 00 00 00 00
701 05 00 00 00 00 00 00 00
701 05 00 00 00 00 00 00 00
701 05 00 00 00 00 00 00 00
701 05 00 00 00 00 00 00 00
081 20 81 00 07 33 00 84 02
081 20 81 00 07 33 00 84 02
081 20 81 00 07 33 00 84 02
081 20 81 00 07 33 00 84 02
081 20 81 00 07 33 00 84 02
081 20 81 00 07 33 00 84 02
081 20 81 00 07 33 00 84 02
081 20 81 00 07 33 00 84 02
081 20 81 00 07 33 00 84 02
081 20 81 00 07 33 00 84 02
081 20 81 00 07 33 00 84 02
081 20 81 00 07 33 00 84 02
081 20 81 00 07 33 00 84 02
081 20 81 00 07 33 00 84 02
081 20 81 00 07 33 00 84 02
081 20 81 00 07 33 00 84 02
