### ISSUE TITLE
CO_sendNMTcommand should return a CO_ReturnError_t, not a uint8_t

### ISSUE THREAD

**Issue by trojanobelix** [CANopenNode/CANopenNode#96]
CO_sendNMTcommand return command is:
### return CO_CANsend(CO->CANmodule[0], NMTM_txBuff); /* 0 = success */
so a CO_ReturnError_t from CO_CANsend is returned

**Comment by martinwag** [comment]
fixed in c0ec1da5ef9d28af37fb36e6b75ff1abde1f00b4
